### ISSUE TITLE
性能有待提升

### ISSUE THREAD

**Issue by alert111** [Chanzi-keji/chanzi#2]
CPU占用率太高十几兆的文件处理起来有点吃力10核32G的Mac

**Comment by Chanzi-keji** [comment]
> CPU占用率太高十几兆的文件处理起来有点吃力10核32G的Mac

调整一下并发线程试试，默认是100个线程，会比较吃CPU

**Comment by Chanzi-keji** [comment]
> CPU占用率太高十几兆的文件处理起来有点吃力10核32G的Mac

我们将在新版本中调小默认的并发线程，以减小资源占用，用户也可以自行调节

**Comment by Chanzi-keji** [comment]
> CPU占用率太高十几兆的文件处理起来有点吃力10核32G的Mac

新版本已经调整了默认的线程数，并且对其他功能也做了一些优化，欢迎您测试使用
