### ISSUE TITLE
docx格式错误

### ISSUE THREAD

**Issue by 2028383846** [Chanzi-keji/chanzi#3]
导出报告时，是docx格式，打开错误。手动改为doc格式时正确打开
![image](https://github.com/user-attachments/assets/8bdf9df7-9957-4c62-b0e5-149639f8029d)
![image](https://github.com/user-attachments/assets/8472b83d-ed03-45a8-9f17-98cac6d40f41)

**Comment by Chanzi-keji** [comment]
感谢反馈，您的系统版本和office版本方便提供一下吗，我们看一下

**Comment by Chanzi-keji** [comment]
我们已经在新版本中修改默认扩展名为doc
