### ISSUE TITLE
开启反编译处增加功能

### ISSUE THREAD

**Issue by cwkiller** [Chanzi-keji/chanzi#5]
![image](https://github.com/user-attachments/assets/3b9fd420-6a11-4000-a5c9-20c34828d727)
大多数项目自己写的class都有一个或几个比较固定的包名，可以在这个地方加一个功能填入一个或多个包名然后用户选择目录自动扫描classes和jar里的符合包名的class反编译

**Comment by Chanzi-keji** [comment]
> ![image](https://private-user-images.githubusercontent.com/19302055/382333048-3b9fd420-6a11-4000-a5c9-20c34828d727.png 大多数项目自己写的class都有一个或几个比较固定的包名，可以在这个地方加一个功能填入一个或多个包名然后用户选择目录自动扫描classes和jar里的符合包名的class反编译

感谢您的反馈，这个需求我们看看怎么优化。 您的目标是希望能够快速筛选需要反编译的类是吧。 目前可以结合排序功能、手动选择，如果class jar量特别大，选起来确实还是麻烦一些，我们考虑下怎么优化

**Comment by Chanzi-keji** [comment]
> ![image](https://private-user-images.githubusercontent.com/19302055/382333048-3b9fd420-6a11-4000-a5c9-20c34828d727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTg1NTUsIm5iZiI6MTczMTI5ODI1NSwicGF0aCI6Ii8xOTMwMjA1NS8zODIzMzMwNDgtM2I5ZmQ0MjAtNmExMS00MDAwLWE1YzktMjBjMzQ4MjhkNzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA0MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3Y2Q2M2E0OWZmYjc1Y2I1MDMwMTFiMmFjM2E4MTUxNzA3ODMwMmVkM2FiNjE5Y2YwZjNmM2Y3MjgxZWU0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kL1mqszxQEegHMG9Lu1Sozf7N4v9sdVq7gYZaJI5tvs) 大多数项目自己写的class都有一个或几个比较固定的包名，可以在这个地方加一个功能填入一个或多个包名然后用户选择目录自动扫描classes和jar里的符合包名的class反编译

针对jar文件已经增加按照包进行选择反编译范围，另外新建任务时可以在右键菜单根据关键字快速勾选需要反编译的包 类路径
