### ISSUE TITLE
MSI安装失败

### ISSUE THREAD

**Issue by jiakun02** [Chanzi-keji/chanzi#6]
我的windows10系统安装失败
![铲子无法安装](https://github.com/user-attachments/assets/a4bd2a2a-d1cb-471e-abf9-20e999218421)
我的系统信息如下:
![系统信息](https://github.com/user-attachments/assets/9ee8951c-d763-4c66-b4dc-da1231dbfdab)

**Comment by Chanzi-keji** [comment]
> 我的windows10系统安装失败 ![铲子无法安装](https://private-user-images.githubusercontent.com/187091554/382456296-a4bd2a2a-d1cb-471e-abf9-20e999218421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2Mjk2LWE0YmQyYTJhLWQxY2ItNDcxZS1hYmY5LTIwZTk5OTIxODQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEyYjc0YmNkN2Y0YjFkNzQ3NjY0NDAxZDQ5ODIxYTRjY2E2YjhiNWNmZWQ3MjkxOWU0ZDY1ZTEyOGVmMTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.McBfUDPI_PiI07Kr4mzmzdajKpzKt_BcNEvyNQ4ZJCU) 我的系统信息如下: ![系统信息](https://private-user-images.githubusercontent.com/187091554/382456308-9ee8951c-d763-4c66-b4dc-da1231dbfdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2MzA4LTllZTg5NTFjLWQ3NjMtNGM2Ni1iNGRjLWRhMTIzMWRiZmRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWY1NTc1NjQ3NzI3OGE3ZWNlNmU5MjRhNTJjOTBjNTVjNzBkZjlhYWYwZDA2NDkwMmQ5Y2M2NjU0MGQ1ZDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3XvgA8JOc3dyT0-QPOOJpf5W7YQ98KHX79M5Eyl8pyA)

您是在 GitHub 下载的吗，还是云盘呢？ 我们测试一下

**Comment by jiakun02** [comment]
是github下载的

**Comment by jiakun02** [comment]
> > 我的windows10系统安装失败 ![铲子无法安装](https://private-user-images.githubusercontent.com/187091554/382456296-a4bd2a2a-d1cb-471e-abf9-20e999218421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2Mjk2LWE0YmQyYTJhLWQxY2ItNDcxZS1hYmY5LTIwZTk5OTIxODQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEyYjc0YmNkN2Y0YjFkNzQ3NjY0NDAxZDQ5ODIxYTRjY2E2YjhiNWNmZWQ3MjkxOWU0ZDY1ZTEyOGVmMTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.McBfUDPI_PiI07Kr4mzmzdajKpzKt_BcNEvyNQ4ZJCU) 我的系统信息如下: ![系统信息](https://private-user-images.githubusercontent.com/187091554/382456308-9ee8951c-d763-4c66-b4dc-da1231dbfdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2MzA4LTllZTg5NTFjLWQ3NjMtNGM2Ni1iNGRjLWRhMTIzMWRiZmRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWY1NTc1NjQ3NzI3OGE3ZWNlNmU5MjRhNTJjOTBjNTVjNzBkZjlhYWYwZDA2NDkwMmQ5Y2M2NjU0MGQ1ZDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3XvgA8JOc3dyT0-QPOOJpf5W7YQ98KHX79M5Eyl8pyA)
> 
> 您是在 GitHub 下载的吗，还是云盘呢？ 我们测试一下

是github下载的

**Comment by Chanzi-keji** [comment]
> > > 我的windows10系统安装失败 ![铲子无法安装](https://private-user-images.githubusercontent.com/187091554/382456296-a4bd2a2a-d1cb-471e-abf9-20e999218421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2Mjk2LWE0YmQyYTJhLWQxY2ItNDcxZS1hYmY5LTIwZTk5OTIxODQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEyYjc0YmNkN2Y0YjFkNzQ3NjY0NDAxZDQ5ODIxYTRjY2E2YjhiNWNmZWQ3MjkxOWU0ZDY1ZTEyOGVmMTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.McBfUDPI_PiI07Kr4mzmzdajKpzKt_BcNEvyNQ4ZJCU) 我的系统信息如下: ![系统信息](https://private-user-images.githubusercontent.com/187091554/382456308-9ee8951c-d763-4c66-b4dc-da1231dbfdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2MzA4LTllZTg5NTFjLWQ3NjMtNGM2Ni1iNGRjLWRhMTIzMWRiZmRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWY1NTc1NjQ3NzI3OGE3ZWNlNmU5MjRhNTJjOTBjNTVjNzBkZjlhYWYwZDA2NDkwMmQ5Y2M2NjU0MGQ1ZDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3XvgA8JOc3dyT0-QPOOJpf5W7YQ98KHX79M5Eyl8pyA)
> > 
> > 
> > 您是在 GitHub 下载的吗，还是云盘呢？ 我们测试一下
> 
> 是github下载的

我们这边刚刚从 GitHub 下载了 2024.2.2 版本，安装是正常的。您再重新下载一下试试呢？或者从云盘下载试试。

**Comment by jiakun02** [comment]
> > > > 我的windows10系统安装失败 ![铲子无法安装](https://private-user-images.githubusercontent.com/187091554/382456296-a4bd2a2a-d1cb-471e-abf9-20e999218421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2Mjk2LWE0YmQyYTJhLWQxY2ItNDcxZS1hYmY5LTIwZTk5OTIxODQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEyYjc0YmNkN2Y0YjFkNzQ3NjY0NDAxZDQ5ODIxYTRjY2E2YjhiNWNmZWQ3MjkxOWU0ZDY1ZTEyOGVmMTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.McBfUDPI_PiI07Kr4mzmzdajKpzKt_BcNEvyNQ4ZJCU) 我的系统信息如下: ![系统信息](https://private-user-images.githubusercontent.com/187091554/382456308-9ee8951c-d763-4c66-b4dc-da1231dbfdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2MzA4LTllZTg5NTFjLWQ3NjMtNGM2Ni1iNGRjLWRhMTIzMWRiZmRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWY1NTc1NjQ3NzI3OGE3ZWNlNmU5MjRhNTJjOTBjNTVjNzBkZjlhYWYwZDA2NDkwMmQ5Y2M2NjU0MGQ1ZDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3XvgA8JOc3dyT0-QPOOJpf5W7YQ98KHX79M5Eyl8pyA)
> > > 
> > > 
> > > 您是在 GitHub 下载的吗，还是云盘呢？ 我们测试一下
> > 
> > 
> > 是github下载的
> 
> 我们这边刚刚从 GitHub 下载了 2024.2.2 版本，安装是正常的。您再重新下载一下试试呢？或者从云盘下载试试。

不能装云盘，我再下载试试

**Comment by jiakun02** [comment]
> > > > > 我的windows10系统安装失败 ![铲子无法安装](https://private-user-images.githubusercontent.com/187091554/382456296-a4bd2a2a-d1cb-471e-abf9-20e999218421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2Mjk2LWE0YmQyYTJhLWQxY2ItNDcxZS1hYmY5LTIwZTk5OTIxODQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEyYjc0YmNkN2Y0YjFkNzQ3NjY0NDAxZDQ5ODIxYTRjY2E2YjhiNWNmZWQ3MjkxOWU0ZDY1ZTEyOGVmMTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.McBfUDPI_PiI07Kr4mzmzdajKpzKt_BcNEvyNQ4ZJCU) 我的系统信息如下: ![系统信息](https://private-user-images.githubusercontent.com/187091554/382456308-9ee8951c-d763-4c66-b4dc-da1231dbfdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2MzA4LTllZTg5NTFjLWQ3NjMtNGM2Ni1iNGRjLWRhMTIzMWRiZmRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWY1NTc1NjQ3NzI3OGE3ZWNlNmU5MjRhNTJjOTBjNTVjNzBkZjlhYWYwZDA2NDkwMmQ5Y2M2NjU0MGQ1ZDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3XvgA8JOc3dyT0-QPOOJpf5W7YQ98KHX79M5Eyl8pyA)
> > > > 
> > > > 
> > > > 您是在 GitHub 下载的吗，还是云盘呢？ 我们测试一下
> > > 
> > > 
> > > 是github下载的
> > 
> > 
> > 我们这边刚刚从 GitHub 下载了 2024.2.2 版本，安装是正常的。您再重新下载一下试试呢？或者从云盘下载试试。
> 
> 不能装云盘，我再下载试试

正常了

**Comment by Chanzi-keji** [comment]
> > > > > > 我的windows10系统安装失败 ![铲子无法安装](https://private-user-images.githubusercontent.com/187091554/382456296-a4bd2a2a-d1cb-471e-abf9-20e999218421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2Mjk2LWE0YmQyYTJhLWQxY2ItNDcxZS1hYmY5LTIwZTk5OTIxODQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEyYjc0YmNkN2Y0YjFkNzQ3NjY0NDAxZDQ5ODIxYTRjY2E2YjhiNWNmZWQ3MjkxOWU0ZDY1ZTEyOGVmMTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.McBfUDPI_PiI07Kr4mzmzdajKpzKt_BcNEvyNQ4ZJCU) 我的系统信息如下: ![系统信息](https://private-user-images.githubusercontent.com/187091554/382456308-9ee8951c-d763-4c66-b4dc-da1231dbfdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQwMTMsIm5iZiI6MTczMDU0MzcxMywicGF0aCI6Ii8xODcwOTE1NTQvMzgyNDU2MzA4LTllZTg5NTFjLWQ3NjMtNGM2Ni1iNGRjLWRhMTIzMWRiZmRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWY1NTc1NjQ3NzI3OGE3ZWNlNmU5MjRhNTJjOTBjNTVjNzBkZjlhYWYwZDA2NDkwMmQ5Y2M2NjU0MGQ1ZDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3XvgA8JOc3dyT0-QPOOJpf5W7YQ98KHX79M5Eyl8pyA)
> > > > > 
> > > > > 
> > > > > 您是在 GitHub 下载的吗，还是云盘呢？ 我们测试一下
> > > > 
> > > > 
> > > > 是github下载的
> > > 
> > > 
> > > 我们这边刚刚从 GitHub 下载了 2024.2.2 版本，安装是正常的。您再重新下载一下试试呢？或者从云盘下载试试。
> > 
> > 
> > 不能装云盘，我再下载试试
> 
> 正常了
好的，感谢您的反馈，有问题您随时联系
