### ISSUE TITLE
登录方式

### ISSUE THREAD

**Issue by 0xAcctracy** [Chanzi-keji/chanzi#7]
为啥要用微信登陆，很不友好。工具跟人分离开不好吗

**Comment by Chanzi-keji** [comment]
> 为啥要用微信登陆，很不友好。工具跟人分离开不好吗

您说的不友好具体指什么呢？
我们后边会优化一下，避免每次打开都登录

**Comment by 0xAcctracy** [comment]
比如工作电脑，公用电脑，不太愿意去使用个人相关账号登陆。

**Comment by Chanzi-keji** [comment]
> 比如工作电脑，公用电脑，不太愿意去使用个人相关账号登陆。

嗯，了解了，目前整个软件的设计，包括登录支付都是采用的微信。 

目前已经提供了退出登录功能，另外扫码登录的过程中不会不会获取，更不会存储您的个人信息，比如头像昵称之类的。不知道能否打消您的顾虑。
