### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by PumpkinBridge** [Chanzi-keji/chanzi#8]
感觉可以支持一个在线版本更新功能，每次收到更新的消息要重新来GitHub下载

**Comment by Chanzi-keji** [comment]
> 感觉可以支持一个在线版本更新功能，每次收到更新的消息要重新来GitHub下载

感谢您的反馈，这个功能也在计划之内，只是优先级较低，核心功能优化完善后会加一下

**Comment by Chanzi-keji** [comment]
> 感觉可以支持一个在线版本更新功能，每次收到更新的消息要重新来GitHub下载

目前最新版本 2024.2.6 在状态栏增加了新版本提醒
